### ISSUE TITLE
Move page click handler to parent element so click target is larger

### ISSUE THREAD

**Issue by dnewcome** [AdeleD/react-paginate#81] opened 2016-05-17 19:16 UTC
I'm proposing that the click handler be moved from the `a` element up to the `li` element. The current click target in most cases will be a single numeral. I needed to support a larger click target for my use case so I moved the click handler up to the parent element.

PR: https://github.com/AdeleD/react-paginate/pull/82

**Comment by DanielSundberg** [comment] 2016-06-03 06:37
Yes I would like this to be merged!

**Comment by amitava82** [comment] 2016-06-20 04:33
This is major usability issue and needs to be fixed.

**Comment by AdeleD** [comment] 2016-06-20 20:30
I'm not sure to understand what the problem is. In a semantic point of view, the click have to be on the element <a>. I think this is a CSS issue: if you want a larger click target you can set the CSS attribute `display: block` on each <a>, don't you think?
But maybe there is another reason I don't understand?

**Comment by dnewcome** [comment] 2016-06-20 20:53
For the previous and next buttons, the click handler is already being assigned to the `li` in the existing code like this:
https://github.com/AdeleD/react-paginate/blob/master/react_components/PaginationBoxView.js#L197

What I'm proposing here just does the same for the individual page `li` elements. Semantically, yes JS is overriding the behavior of `<a>`. I chose changing the `onClick` location since it seemed more consistent with the existing approach. Let me know.

**Comment by AdeleD** [comment] 2016-06-20 21:21
Ok, thank you for the explanation. Let's merge.

**Comment by AdeleD** [comment] 2016-06-20 21:41
Done. And sorry for the delay... :confused:

**Comment by dnewcome** [comment] 2016-06-20 21:43
np thanks!

**Closed** 2016-07-14 19:50 UTC

**Comment by hmontes** [comment] 2017-01-31 19:09
+1. With React is not necessary the "onClick" handler in <a>. Instead, you can move to <li> (and for theming. Is much more confortable)
